gki_defconfig: Add back CONFGI_KFENCE
i met an error while building lineageos 22.2 june spl, and the compiler require to add CONFIG_KFENCE

ERROR: files are incompatible: Runtime info and framework compatibility matrix are incompatible: No compatible kernel requirement found (kernel FCM version = 8).
For kernel requirements at matrix level 8, Kernel config errors:
    Missing config CONFIG_KFENCE
: Success
INCOMPATIBLE